/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author BioniDKU
 */
public class ShopUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopUI.class.getName());

    /**
     * Creates new form DashUIAdmin
     */
    public ShopUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HCt = new javax.swing.JLayeredPane();
        ControlStrip = new javax.swing.JPanel();
        btnLOGOUT = new javax.swing.JButton();
        TabsUI = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLOGOUT.setText("Log out");
        btnLOGOUT.setBorder(null);
        btnLOGOUT.addActionListener(this::btnLOGOUTActionPerformed);

        javax.swing.GroupLayout ControlStripLayout = new javax.swing.GroupLayout(ControlStrip);
        ControlStrip.setLayout(ControlStripLayout);
        ControlStripLayout.setHorizontalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ControlStripLayout.setVerticalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLOGOUT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        TabsUI.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        TabsUI.setAutoscrolls(true);

        HCt.setLayer(ControlStrip, javax.swing.JLayeredPane.POPUP_LAYER);
        HCt.setLayer(TabsUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HCtLayout = new javax.swing.GroupLayout(HCt);
        HCt.setLayout(HCtLayout);
        HCtLayout.setHorizontalGroup(
            HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsUI)
            .addGroup(HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HCtLayout.createSequentialGroup()
                    .addGap(0, 952, Short.MAX_VALUE)
                    .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HCtLayout.setVerticalGroup(
            HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsUI, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HCtLayout.createSequentialGroup()
                    .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 742, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HCt)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HCt)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Flatlaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShopUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlStrip;
    private javax.swing.JLayeredPane HCt;
    private javax.swing.JTabbedPane TabsUI;
    private javax.swing.JButton btnLOGOUT;
    // End of variables declaration//GEN-END:variables
}
