/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.ShopTabs;

import javax.swing.JOptionPane;
import controller.OrderCtrl;
import controller.ProductCtrl;
import model.Product;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Products extends javax.swing.JPanel {

    private ProductCtrl productCtrl = new ProductCtrl();
    private OrderCtrl orderCtrl = new OrderCtrl();
    private DefaultTableModel tableModel;

    public Products() {
        initComponents();
        loadData();
        
        if(btnF5 != null) btnF5.addActionListener(e -> loadData());
        if(btnDel != null) btnDel.addActionListener(e -> buySelectedProduct());
    }

    private void loadData() {
        tableModel = (DefaultTableModel) Table.getModel();
        tableModel.setRowCount(0);
        ArrayList<Product> list = productCtrl.getAllProducts();
        for (Product p : list) {
            if (p.getQuantity() > 0) {
                tableModel.addRow(new Object[]{
                    p.getId(), p.getName(), p.getCategory(), 
                    p.getQuantity(), p.getPrice()
                });
            }
        }
    }

    private void buySelectedProduct() {
        int selectedRow = Table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to buy!");
            return;
        }

        int productId = (int) Table.getValueAt(selectedRow, 0);
        String prodName = (String) Table.getValueAt(selectedRow, 1);
        int currentStock = (int) Table.getValueAt(selectedRow, 3);
        double price = (double) Table.getValueAt(selectedRow, 4);

        String inputQty = JOptionPane.showInputDialog(this, 
                "Buying: " + prodName + "\nPrice: $" + price + "\nAvailable: " + currentStock + "\n\nEnter Quantity:");
        
        if (inputQty == null || inputQty.isEmpty()) return;

        try {
            int buyQty = Integer.parseInt(inputQty);

            if (buyQty <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be > 0");
                return;
            }
            if (buyQty > currentStock) {
                JOptionPane.showMessageDialog(this, "Not enough stock! Only " + currentStock + " left.");
                return;
            }

            double total = buyQty * price;
            
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Total cost: $" + total + ". Confirm purchase?");

            if (confirm == JOptionPane.YES_OPTION) {
                int customerId = 2;
                orderCtrl.addProductOrder(customerId, productId, buyQty, total);

                int newStock = currentStock - buyQty;
                productCtrl.updateProductQuantity(productId, newStock);

                JOptionPane.showMessageDialog(this, "Purchase successful!");
                loadData();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity number!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableView = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ControlStrip = new javax.swing.JPanel();
        btnF5 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 720));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKN", "Name", "Category", "Qty", "Price per item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setColumnSelectionAllowed(true);
        Table.setFillsViewportHeight(true);
        Table.setShowGrid(true);
        Table.setShowHorizontalLines(false);
        Table.getTableHeader().setReorderingAllowed(false);
        TableView.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setMinWidth(16);
            Table.getColumnModel().getColumn(0).setPreferredWidth(48);
            Table.getColumnModel().getColumn(0).setMaxWidth(64);
            Table.getColumnModel().getColumn(2).setMinWidth(16);
            Table.getColumnModel().getColumn(2).setPreferredWidth(256);
            Table.getColumnModel().getColumn(2).setMaxWidth(512);
            Table.getColumnModel().getColumn(3).setMinWidth(16);
            Table.getColumnModel().getColumn(3).setPreferredWidth(48);
            Table.getColumnModel().getColumn(3).setMaxWidth(64);
            Table.getColumnModel().getColumn(4).setMinWidth(16);
            Table.getColumnModel().getColumn(4).setPreferredWidth(128);
            Table.getColumnModel().getColumn(4).setMaxWidth(256);
        }

        btnF5.setText("Refresh");

        btnDel.setText("Buy selected");

        javax.swing.GroupLayout ControlStripLayout = new javax.swing.GroupLayout(ControlStrip);
        ControlStrip.setLayout(ControlStripLayout);
        ControlStripLayout.setHorizontalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlStripLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnF5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap())
        );
        ControlStripLayout.setVerticalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF5)
                    .addComponent(btnDel))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlStrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TableView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TableView, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlStrip;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TableView;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnF5;
    // End of variables declaration//GEN-END:variables
}
