/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.DashTabs;
import controller.PetCtrl;
import model.Pet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pets extends javax.swing.JPanel {

    private PetCtrl controller = new PetCtrl();
    private DefaultTableModel tableModel;

    public Pets() {
        initComponents();
        
        
        loadData();
        
        btnF5.addActionListener(e -> loadData());
        btnAdd.addActionListener(e -> addPet());
        btnDel.addActionListener(e -> deletePet());
    }

    private void loadData() {
        tableModel = (DefaultTableModel) Table.getModel();
        tableModel.setRowCount(0);

        ArrayList<Pet> list = controller.getAllPets();

        for (Pet p : list) {
            String extraInfo = p.getBreed(); 

            tableModel.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getType(),
                extraInfo,
                p.getAge(),
                p.getPrice(),
                true
            });
        }
    }

    private void addPet() {
        try {
            String name = txtName.getText();
            String type = txtType.getSelectedItem().toString();
            String breed = txtBrd.getText();
            int age = Integer.parseInt(txtAge.getText());
            double price = Double.parseDouble(txtPrice.getText());

            controller.addPet(name, age, price, type, breed);
            
            JOptionPane.showMessageDialog(this, "Added successfully!");
            loadData();
            
            txtName.setText("");
            txtBrd.setText("");
            txtAge.setText("");
            txtPrice.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age and Price must be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void deletePet() {
        int selectedRow = Table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to delete.");
            return;
        }

        int id = (int) Table.getValueAt(selectedRow, 0);
        
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Pet ID: " + id + "?");
        if (confirm == JOptionPane.YES_OPTION) {
            controller.deletePet(id);
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableView = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ControlStrip = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelType = new javax.swing.JLabel();
        txtType = new javax.swing.JComboBox<>();
        labelBrd = new javax.swing.JLabel();
        txtBrd = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        labelPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 720));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKN", "Name", "Type", "Breed", "Age", "Price", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.setColumnSelectionAllowed(true);
        Table.setFillsViewportHeight(true);
        Table.setShowGrid(true);
        Table.setShowHorizontalLines(false);
        Table.getTableHeader().setReorderingAllowed(false);
        TableView.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setMinWidth(16);
            Table.getColumnModel().getColumn(0).setPreferredWidth(48);
            Table.getColumnModel().getColumn(0).setMaxWidth(64);
            Table.getColumnModel().getColumn(2).setMinWidth(16);
            Table.getColumnModel().getColumn(2).setPreferredWidth(64);
            Table.getColumnModel().getColumn(2).setMaxWidth(64);
            Table.getColumnModel().getColumn(4).setMinWidth(16);
            Table.getColumnModel().getColumn(4).setPreferredWidth(48);
            Table.getColumnModel().getColumn(4).setMaxWidth(64);
            Table.getColumnModel().getColumn(5).setMinWidth(16);
            Table.getColumnModel().getColumn(5).setPreferredWidth(64);
            Table.getColumnModel().getColumn(5).setMaxWidth(128);
            Table.getColumnModel().getColumn(6).setMinWidth(16);
            Table.getColumnModel().getColumn(6).setPreferredWidth(64);
            Table.getColumnModel().getColumn(6).setMaxWidth(128);
        }

        labelName.setText("Name:");

        txtName.addActionListener(this::txtNameActionPerformed);

        labelType.setText("Type:");

        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat" }));
        txtType.setToolTipText("");
        txtType.addActionListener(this::txtTypeActionPerformed);

        labelBrd.setText("Breed:");

        txtBrd.addActionListener(this::txtBrdActionPerformed);

        labelAge.setText("Age:");

        labelPrice.setText("Price:");

        btnAdd.setText("Add Pet");

        btnF5.setText("Refresh");

        btnDel.setText("Delete selected");

        javax.swing.GroupLayout ControlStripLayout = new javax.swing.GroupLayout(ControlStrip);
        ControlStrip.setLayout(ControlStripLayout);
        ControlStripLayout.setHorizontalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlStripLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelBrd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBrd, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnF5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap())
        );
        ControlStripLayout.setVerticalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelType)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnF5)
                    .addComponent(btnDel)
                    .addComponent(labelBrd)
                    .addComponent(txtBrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlStrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TableView)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TableView, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtBrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlStrip;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TableView;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnF5;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelBrd;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelType;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBrd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JComboBox<String> txtType;
    // End of variables declaration//GEN-END:variables
}