/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.DashTabs;

import controller.ProductCtrl;
import model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Products extends javax.swing.JPanel {

    private controller.ProductCtrl controller = new controller.ProductCtrl();
    private javax.swing.table.DefaultTableModel tableModel;

    public Products() {
        initComponents();
        
        loadData();
        
        btnF5.addActionListener(e -> loadData());
        btnAdd.addActionListener(e -> addProduct());
        btnDel.addActionListener(e -> deleteProduct());
    }

    private void loadData() {
        tableModel = (DefaultTableModel) Table.getModel();
        tableModel.setRowCount(0);

        ArrayList<Product> list = controller.getAllProducts();

        for (Product p : list) {
            
            tableModel.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getCategory(),
                p.getQuantity(),
                p.getPrice()
            });
        }
    }

    
    private void addProduct() {
        try {
            String name = txtName.getText().trim();
            
            
            String category = txtCategory.getText().trim(); 
            
            if (category.isEmpty()) {
                category = "General";
            }

            String qtyText = txtQty.getText().trim();
            String priceText = txtPrice.getText().trim();

            if (name.isEmpty() || qtyText.isEmpty() || priceText.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Please fill in Name, Quantity and Price.");
                 return;
            }

            int quantity = Integer.parseInt(qtyText);
            double price = Double.parseDouble(priceText);

            controller.addProduct(name, price, quantity, category); 
            
            JOptionPane.showMessageDialog(this, "Product added successfully!");
            loadData();
            
            txtName.setText("");
            txtCategory.setText("");
            txtQty.setText("");
            txtPrice.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity and Price must be valid numbers!", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void deleteProduct() {
        
        int selectedRow = Table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to delete.");
            return;
        }

        
        int id = (int) Table.getValueAt(selectedRow, 0);
        String name = (String) Table.getValueAt(selectedRow, 1);
        
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Delete product: " + name + "?", 
                "Confirm Delete", 
                JOptionPane.YES_NO_OPTION);
                
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                controller.deleteProduct(id);
                
                loadData();
                JOptionPane.showMessageDialog(this, "Deleted successfully!");
                
            } catch (Exception e) {
                
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableView = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ControlStrip = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        labelPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1024, 720));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKN", "Name", "Category", "Qty", "Price per item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.setColumnSelectionAllowed(true);
        Table.setFillsViewportHeight(true);
        Table.setShowGrid(true);
        Table.setShowHorizontalLines(false);
        Table.getTableHeader().setReorderingAllowed(false);
        TableView.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setMinWidth(16);
            Table.getColumnModel().getColumn(0).setPreferredWidth(48);
            Table.getColumnModel().getColumn(0).setMaxWidth(64);
            Table.getColumnModel().getColumn(2).setMinWidth(16);
            Table.getColumnModel().getColumn(2).setPreferredWidth(256);
            Table.getColumnModel().getColumn(2).setMaxWidth(512);
            Table.getColumnModel().getColumn(3).setMinWidth(16);
            Table.getColumnModel().getColumn(3).setPreferredWidth(48);
            Table.getColumnModel().getColumn(3).setMaxWidth(64);
            Table.getColumnModel().getColumn(4).setMinWidth(16);
            Table.getColumnModel().getColumn(4).setPreferredWidth(128);
            Table.getColumnModel().getColumn(4).setMaxWidth(256);
        }

        labelName.setText("Name:");

        txtName.addActionListener(this::txtNameActionPerformed);

        labelQty.setText("Qty:");

        txtQty.addActionListener(this::txtQtyActionPerformed);

        labelPrice.setText("Price:");

        btnAdd.setText("Add Item");

        btnF5.setText("Refresh");

        btnDel.setText("Delete selected");

        jLabel1.setText("Category");

        txtCategory.addActionListener(this::txtCategoryActionPerformed);

        javax.swing.GroupLayout ControlStripLayout = new javax.swing.GroupLayout(ControlStrip);
        ControlStrip.setLayout(ControlStripLayout);
        ControlStripLayout.setHorizontalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlStripLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnF5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap())
        );
        ControlStripLayout.setVerticalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnF5)
                    .addComponent(btnDel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlStrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TableView)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TableView, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlStrip;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TableView;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnF5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQty;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}