/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.DashTabs;

/**
 *
 * @author BioniDKU
 */
public class Records extends javax.swing.JPanel {

    /**
     * Creates new form Records
     */
    public Records() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HCt = new javax.swing.JLayeredPane();
        ControlStrip = new javax.swing.JPanel();
        btnF5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TabsUI = new javax.swing.JTabbedPane();
        Pets = new javax.swing.JPanel();
        TableView1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        Products = new javax.swing.JPanel();
        TableView2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();

        btnF5.setText("Refresh");

        jLabel1.setText("Total orders: {numOrders} - Total revenue: {sumRevenue}");

        javax.swing.GroupLayout ControlStripLayout = new javax.swing.GroupLayout(ControlStrip);
        ControlStrip.setLayout(ControlStripLayout);
        ControlStripLayout.setHorizontalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addContainerGap(498, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnF5)
                .addContainerGap())
        );
        ControlStripLayout.setVerticalGroup(
            ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlStripLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF5)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SKU", "SKU Name", "Type", "Customer ID", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1.setColumnSelectionAllowed(true);
        Table1.setFillsViewportHeight(true);
        Table1.setShowGrid(true);
        Table1.setShowHorizontalLines(false);
        Table1.getTableHeader().setReorderingAllowed(false);
        TableView1.setViewportView(Table1);
        Table1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(0).setMinWidth(16);
            Table1.getColumnModel().getColumn(0).setPreferredWidth(48);
            Table1.getColumnModel().getColumn(0).setMaxWidth(64);
            Table1.getColumnModel().getColumn(1).setMinWidth(16);
            Table1.getColumnModel().getColumn(1).setPreferredWidth(48);
            Table1.getColumnModel().getColumn(1).setMaxWidth(64);
            Table1.getColumnModel().getColumn(3).setMinWidth(16);
            Table1.getColumnModel().getColumn(3).setPreferredWidth(48);
            Table1.getColumnModel().getColumn(3).setMaxWidth(64);
            Table1.getColumnModel().getColumn(4).setMinWidth(16);
            Table1.getColumnModel().getColumn(4).setPreferredWidth(128);
            Table1.getColumnModel().getColumn(4).setMaxWidth(256);
            Table1.getColumnModel().getColumn(5).setPreferredWidth(64);
            Table1.getColumnModel().getColumn(5).setMaxWidth(128);
        }

        javax.swing.GroupLayout PetsLayout = new javax.swing.GroupLayout(Pets);
        Pets.setLayout(PetsLayout);
        PetsLayout.setHorizontalGroup(
            PetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableView1)
        );
        PetsLayout.setVerticalGroup(
            PetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableView1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        TabsUI.addTab("Pets", Pets);

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SKU", "SKU Name", "Qty", "Customer ID", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table2.setFillsViewportHeight(true);
        Table2.setShowGrid(true);
        Table2.setShowHorizontalLines(false);
        Table2.getTableHeader().setReorderingAllowed(false);
        TableView2.setViewportView(Table2);
        Table2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table2.getColumnModel().getColumnCount() > 0) {
            Table2.getColumnModel().getColumn(0).setMinWidth(16);
            Table2.getColumnModel().getColumn(0).setPreferredWidth(48);
            Table2.getColumnModel().getColumn(0).setMaxWidth(64);
            Table2.getColumnModel().getColumn(1).setMinWidth(16);
            Table2.getColumnModel().getColumn(1).setPreferredWidth(48);
            Table2.getColumnModel().getColumn(1).setMaxWidth(64);
            Table2.getColumnModel().getColumn(3).setMinWidth(16);
            Table2.getColumnModel().getColumn(3).setPreferredWidth(48);
            Table2.getColumnModel().getColumn(3).setMaxWidth(64);
            Table2.getColumnModel().getColumn(4).setMinWidth(16);
            Table2.getColumnModel().getColumn(4).setPreferredWidth(128);
            Table2.getColumnModel().getColumn(4).setMaxWidth(256);
            Table2.getColumnModel().getColumn(5).setPreferredWidth(64);
            Table2.getColumnModel().getColumn(5).setMaxWidth(128);
        }

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableView2)
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableView2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        TabsUI.addTab("Groceries", Products);

        HCt.setLayer(ControlStrip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HCt.setLayer(TabsUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HCtLayout = new javax.swing.GroupLayout(HCt);
        HCt.setLayout(HCtLayout);
        HCtLayout.setHorizontalGroup(
            HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsUI)
            .addGroup(HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HCtLayout.createSequentialGroup()
                    .addGap(0, 136, Short.MAX_VALUE)
                    .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HCtLayout.setVerticalGroup(
            HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsUI)
            .addGroup(HCtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HCtLayout.createSequentialGroup()
                    .addComponent(ControlStrip, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 686, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HCt)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HCt)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlStrip;
    private javax.swing.JLayeredPane HCt;
    private javax.swing.JPanel Pets;
    private javax.swing.JPanel Products;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JScrollPane TableView1;
    private javax.swing.JScrollPane TableView2;
    private javax.swing.JTabbedPane TabsUI;
    private javax.swing.JButton btnF5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
